version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql-data:/var/lib/mysql

  wordpress1:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: r00t
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress1:/var/www/html
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
      docker-entrypoint.sh apache2-foreground"

  wordpress2:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: r00t
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress2:/var/www/html
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
      docker-entrypoint.sh apache2-foreground"

  wordpress3:
    image: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: r00t
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress3:/var/www/html
    command: >
      bash -c "chown -R www-data:www-data /var/www/html &&
      docker-entrypoint.sh apache2-foreground"