scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'locust'
    scrape_interval: 5s
    static_configs:
      - targets: ['locust-exporter:9646']
